language: php
sudo: false
php:
 - 5.4
 - 5.5
 - 5.6
 - hhvm
 - nightly
before_script: composer install
after_script:
 - vendor/bin/test-reporter
matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true
addons:
  codeclimate: true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8229d26a4f90bcc6cd67
script: vendor/bin/phpunit --bootstrap ./tests/bootstrap.php --coverage-clover build/logs/clover.xml tests
